server:
  port: 8080
spring:
  profiles:
    active: prod,dev,default
  application:
    name: employeeService
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      label: master
      enabled: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
